name: Build

on:
  push:
    branches:
      - master

jobs:
  test-node:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project
      uses: actions/checkout@v2
    - run: |
        date > date.txt
        git config --local user.email "actions@github.com"
        git config --local user.name "${{ github.actor }}"
        git add date.txt
        git commit -m "update!"
        git push
